In [27]:
import numpy as np

# array 1 dimensao
a = np.array([1,2,3,4,5,6])
print("EXEMPLO 1:\narray: ", type(a), "; dimensao: ", a.ndim, "\n")

EXEMPLO 1:
array:  <class 'numpy.ndarray'> ; dimensao:  1 



In [32]:
# array 2 dimensoes
b = np.arange(15).reshape(3,5)
print ("EXEMPLO 2:\narray: arange + reshape: \n", b, "\ndimensao: ", b.ndim)

EXEMPLO 2:
array: arange + reshape: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 
dimensao:  2


In [29]:
# retornar tipos de elementos
print(b.astype(float).dtype)

float64


In [30]:
# retornar tipo de array
# vantagem array: calculo elemento por elemento
print(type(a))

<class 'numpy.ndarray'>


In [34]:
# boolean < int < float < string
# nao esquecer colchetes
# recebe listas

print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# sequencia de uns
print(np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [36]:
# evitar usar empty pq pega numeros aleatorios
print(np.empty((1,2,10)))

[[[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323 3.0e-323
   3.5e-323 4.0e-323 4.4e-323]
  [4.9e-323 5.4e-323 5.9e-323 6.4e-323 6.9e-323 7.4e-323 7.9e-323
   8.4e-323 8.9e-323 9.4e-323]]]


In [38]:
# sequencia de numeros iguais
print(np.ones((3))*3.14)

[3.14 3.14 3.14]


In [40]:
# sequencia aleatoria 1 dimensao
np.random.rand(3)

array([0.58349666, 0.43175568, 0.78610938])

In [42]:
# sequencia aleatoria 3 linhas, 2 colunas
10+ np.random.rand(3,2)

array([[10.95589265, 10.40323929],
       [10.16749395, 10.24660512],
       [10.54019051, 10.70951032]])

In [47]:
# imprime de 1 a 3 em intervalos de 0.5
print(np.arange(1, 3, 0.5))

[1.  1.5 2.  2.5]


In [49]:
# imprime numeros de 0 a 10 limitando a 2 o numero de elementos
print(np.linspace(0,10,2))

[ 0. 10.]


In [56]:
# operacoes com numpy -- MULTIPLICACAO
a = np.array([1,2,3])
b = 2

print("NUMPY MULTIPLICA: {} * {} = {}".format(b,a,b*a))

# se nao usar numpy e multiplicar uma lista por um escalar, a lista vai concatenar N vezes
c = [1,2,3]
print("LISTA REGULAR CONCATENA: {} * {} = {}".format(b,c,b*c))



NUMPY MULTIPLICA: 2 * [1 2 3] = [2 4 6]
LISTA REGULAR CONCATENA: 2 * [1, 2, 3] = [1, 2, 3, 1, 2, 3]


In [59]:
# operacoes com numpy -- SOMA
print("{} + {} = {}".format(b,a,b+a))

2 + [1 2 3] = [3 4 5]


In [60]:
# operacoes com numpy -- SUBTRACAO
print("{} - {} = {}".format(b,a,b-a))

2 - [1 2 3] = [ 1  0 -1]


In [61]:
# operacoes com numpy -- DIVISAO
print("{} / {} = {}".format(b,a,b/a))

2 / [1 2 3] = [2.         1.         0.66666667]


In [62]:
# operacoes com numpy -- EXPONENCIACAO
print("{} ** {} = {}".format(b,a,b**a))

2 ** [1 2 3] = [2 4 8]


In [65]:
# operacoes com 2 listas
d = np.array([2,4,6])
e = np.array([1,2,3])
print("{} ** {} = {}".format(d,e,d**e))

[2 4 6] ** [1 2 3] = [  2  16 216]


In [80]:
# EXERCICIO Mean Squared Error
import math

def vMSE(y_true, y_pred):
    return np.mean((y_pred - y_true)**2)

y_true = np.arange(1000000) + 1
y_pred = y_true - np.random.rand(y_true.shape[0])
print(vMSE(y_true, y_pred))

                                 

0.3332145697578087
