In [25]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7, 8])

print("a: ", a)
print("b: ", b)
print("c: ", c)

a:  [1 2 3]
b:  [4 5 6]
c:  [7 8]


In [26]:
# concatenar unidimensional
print("a + b: ", np.concatenate((a,b)))
print("b + a: ", np.concatenate((b,a)))
print("a + b + c: ", np.concatenate((a,b,c)))

a + b:  [1 2 3 4 5 6]
b + a:  [4 5 6 1 2 3]
a + b + c:  [1 2 3 4 5 6 7 8]


In [32]:
# concatenar multidimensional
# eixos tem que ser iguais. Se concatenar linhas, no. de linhas tem que ser iguais

d = np.floor(10*np.random.random((2,2)))
print("matriz d:\n",d,"\n")

e = np.floor(10*np.random.random((2,2)))
print("matriz b:\n",e,"\n")

# concatena linhas 
print("concatena linhas (axis=0):\n", np.concatenate((d,e), axis=0),"\n")

# concatena colunas 
print("concatena colunas (axis=1):\n", np.concatenate((d,e), axis=1),"\n")

matriz d:
 [[1. 1.]
 [9. 4.]] 

matriz b:
 [[7. 8.]
 [5. 1.]] 

concatena linhas (axis=0):
 [[1. 1.]
 [9. 4.]
 [7. 8.]
 [5. 1.]] 

concatena colunas (axis=1):
 [[1. 1. 7. 8.]
 [9. 4. 5. 1.]] 



In [31]:
# mesma coisa que usar v ou h stack
print("concatena linhas vstack:\n",np.vstack((d,e)),"\n")

print("concatena colunas hstack:\n",np.hstack((d,e)),"\n")

concatena linhas vstack:
 [[7. 3.]
 [1. 5.]
 [7. 4.]
 [3. 6.]] 

concatena colunas hstack:
 [[7. 3. 7. 4.]
 [1. 5. 3. 6.]] 



In [52]:
# criar copias
f = np.floor(10*np.random.random((4,4)))
print("matriz f:\n",d,"\n")

def copia(f):
    print("id de copia:",id(f.copy()))
    
print("id de f:" ,id(f))
copia(f)

h = np.floor(10*np.random.random((4,4)))
print("\n","matriz f:\n",h,"\n")

i = h[:,1:3].copy()
print("id h:",id(h))
print("id i:",id(i),"\n")

print("matriz i:\n",i)

matriz f:
 [[1. 1.]
 [9. 4.]] 

id de f: 4503270944
id de copia: 4743177360

 matriz f:
 [[6. 3. 3. 7.]
 [0. 9. 1. 8.]
 [2. 6. 4. 8.]
 [0. 7. 9. 5.]] 

id h: 4743177360
id i: 4533195840 

matriz i:
 [[3. 3.]
 [9. 1.]
 [6. 4.]
 [7. 9.]]
