In [1]:
import numpy as np

a = np.array([[1.0,2.0],[3.0,4.0]])
print("matriz a:", a)

matriz a: [[1. 2.]
 [3. 4.]]


In [7]:
# matriz transposta
print("matriz transposta 1:\n",a.transpose())
print("matriz transposta 2:\n",a.T)

matriz transposta 1:
 [[1. 3.]
 [2. 4.]]
matriz transposta 2:
 [[1. 3.]
 [2. 4.]]


In [8]:
# inversao de matriz
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# matriz e identidade - todos numeros sao 0 exceto diagonal principal
print(np.eye(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
# multiplicacao de matriz
a = np.array([[1.0,2.0],[3.0,4.0]])
print("multiplicacao de matriz:\n",np.dot(a, np.linalg.inv(a)))

multiplicacao de matriz:
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [16]:
# calculo de autovalores e autovetores
print(np.linalg.eig(a))

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [21]:
# EXERCICIO
x = np.abs(np.random.normal(60, 500, 100))[:,np.newaxis]
w = 2000
y = x * (w - np.random.normal(0, 100, x.shape[0]))[:,np.newaxis]

print("x:\n",x)
print("w:",w)
print("y:\n",y)

x:
 [[ 737.00330667]
 [ 350.45890368]
 [  41.99826016]
 [ 133.4853905 ]
 [ 284.95564554]
 [ 946.63204589]
 [ 791.36021617]
 [  25.01917926]
 [ 492.11455324]
 [ 127.12112822]
 [ 102.27010056]
 [ 742.95510631]
 [ 112.70497111]
 [   5.15072546]
 [ 238.26775743]
 [ 179.9504659 ]
 [ 445.81210056]
 [  73.92116138]
 [1011.88010087]
 [1036.25563107]
 [ 826.64608488]
 [ 159.72821316]
 [1057.26592941]
 [1100.91920261]
 [ 298.39853434]
 [1049.00936683]
 [ 337.01259776]
 [1006.11589584]
 [ 315.42031765]
 [  26.23004842]
 [ 348.1402348 ]
 [ 348.23741223]
 [ 726.95947858]
 [ 341.39603542]
 [  81.98903358]
 [ 614.22209337]
 [ 683.80910579]
 [ 109.70988073]
 [ 186.94822497]
 [ 338.30914312]
 [  98.93735824]
 [ 505.74601043]
 [ 587.58199589]
 [ 107.44541161]
 [  25.38538622]
 [ 113.08274749]
 [ 107.29686287]
 [ 255.21370532]
 [ 132.29799544]
 [ 277.91189819]
 [ 329.07617865]
 [ 121.82248873]
 [ 876.3663655 ]
 [ 781.45093186]
 [ 508.56236178]
 [ 293.80938362]
 [ 118.02499841]
 [ 301.09647596]
 [  17.039

In [24]:
def ajustar(x,y):
    return np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)

ajustar(x,y)

array([[2010.48298457]])