In [39]:
# acessar posicao de dado dentro da lista

import numpy as np

a = (np.arange(16)**2).reshape(4,4)
print(a)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [10]:
# acessar elemento dentro da lista: linha 0 coluna 1
print("Linha 0 e coluna 1: ", a[0,1])
print("Elementos linha 0 a 2 coluna 0: ", a[:3,0])
print("Todos elementos da coluna 0: ",a[:,:1])
print("Ultima linha: ", a[-1])

Linha 0 e coluna 1:  1
Elementos linha 0 a 2 coluna 0:  [ 0 16 64]
Todos elementos da coluna 0:  [[  0]
 [ 16]
 [ 64]
 [144]]
Ultima linha:  [144 169 196 225]


In [20]:
# manipulacao de shape
a = ((np.arange(16))**2).reshape(4,4)

# deixar lista flat - uma unica lina
print("Usando ravel:", a.ravel())
print("Usando reshape:", a.reshape(-1))
print("Transposta:", a.T)

Usando ravel: [  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
Usando reshape: [  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
Transposta: [[  0  16  64 144]
 [  1  25  81 169]
 [  4  36 100 196]
 [  9  49 121 225]]


In [77]:
# truques de indexacao
b = np.arange(12)**2
print("Sem reshape: ",b)

# retornar posicao dos elemtos
indices = np.array([1,1,6,3,5])
print("Retorna posicao dos indices:", b[indices])

# novo exemplo transformando resultado em matriz bidimensional
novo_indice = np.array([[1,6],[3,5]])
print("Retorna indice bidimensional: ", b[novo_indice])

# novo exemplo
c = (np.arange(21)**2).reshape(7,3)
print("\nUsando reshape:", c)

id_linhas = np.array([0,1,5])
id_colunas = np.array([2,1,1])

# retorna posicoes de linhas e colunas informadas acima
print("\nResultado:", c[id_linhas, id_colunas])

# exemplo com slicing - todas as linhas e colunas 0 e 2
print("\nExempl0 slicing: ",c[:,[0,2]])

# teste -- imprimir todas as linhas e colunas de 1 a 2. Coluna 2 nao vai aparecer
print("\nTeste: ",c[:,1:2])

Sem reshape:  [  0   1   4   9  16  25  36  49  64  81 100 121]
Retorna posicao dos indices: [ 1  1 36  9 25]
Retorna indice bidimensional:  [[ 1 36]
 [ 9 25]]

Usando reshape: [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]
 [144 169 196]
 [225 256 289]
 [324 361 400]]

Resultado: [  4  16 256]

Exempl0 slicing:  [[  0   4]
 [  9  25]
 [ 36  64]
 [ 81 121]
 [144 196]
 [225 289]
 [324 400]]

Teste:  [[  1]
 [ 16]
 [ 49]
 [100]
 [169]
 [256]
 [361]]


In [79]:
# retornar booleanos
d = c >= 100
print(d)

# atribuicao de valores
c[d] = 0
print(c)

[[False False False]
 [False False False]
 [False False False]
 [False  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]
 [81  0  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]
